### ISSUE TITLE
Images not found for the dockerfiles

### ISSUE THREAD

**Issue by royteeuwen** [balamaci/blog-ui-testing-container#2]
When I run the docker build.sh, it tells me the images are not found:

Step 0 : FROM balamaci/oracle-jdk8
Pulling repository docker.io/balamaci/oracle-jdk8
Error: image balamaci/oracle-jdk8:latest not found
Sending build context to Docker daemon 8.704 kB
Step 0 : FROM balamaci/oracle-jdk8
Pulling repository docker.io/balamaci/oracle-jdk8
Error: image balamaci/oracle-jdk8:latest not found
Sending build context to Docker daemon 8.704 kB
Step 0 : FROM balamaci/mvn3-jdk8
Pulling repository docker.io/balamaci/mvn3-jdk8
Error: image balamaci/mvn3-jdk8:latest not found

**Comment by balamaci** [comment]
Hi, actually the build.sh script from scripts dir was misleading, instead you should rely on docker-images-build.sh file 
I've removed the misleading file.

**Comment by royteeuwen** [comment]
Hey balmaci,

I am talking about the docker-images-build.sh, didn't even know there was another build.sh.. Please reopen :) 

Greetings,
Roy

**Comment by balamaci** [comment]
Hi, 
Well the first line in the build script is the line that builds the **balamaci/oracle-jdk8** image:
docker build --rm -t balamaci/oracle-jdk8 -f oracle-jdk8.dockerfile .

your output would make sense if the second line that builds the tomcat image(FROM the balamaci/oracle-jdk8)
Step 0 : FROM balamaci/oracle-jdk8
Pulling repository docker.io/balamaci/oracle-jdk8
Error: image balamaci/oracle-jdk8:latest not found
Sending build context to Docker daemon 8.704 kB

reports that it did not find "balamaci/oracle-jdk8" which means that for some reason on your machine it failed the build of oracle-jdk8 image.
I think you should have some indications from the output why it failed to do that.
I've erased and rebuild all the images on mine and it's still finished all the steps.

**Comment by royteeuwen** [comment]
Hey,

Ah ok that seems to be the issue indeed. The first one kept on failing, so I just tried to at least let the following ones succeed, but seeing as they are dependant on the first one that of course will not work. I am now on another network and I got the first one to work, so everything works now.Thanks!

Greetings,
Roy

**Comment by balamaci** [comment]
You're welcome!

**Comment by royteeuwen** [comment]
Hey Serban,

I found two other problems:
- The docker-compose speaks of balmaci/tomcat7 while the docker-images.build.sh makes balmaci/tomcat7-jdk8
- When I change the docker-compose to use balmaci/tomcat7-jdk8 and do "docker-compose run uitests mvn verify"  I get the following error:
  
  Failed to execute goal org.codehaus.cargo:cargo-maven2-plugin:1.4.11:deploy (war-deploy) on project blog-docker-immutable: Execution war-deploy of goal org.codehaus.cargo:cargo-maven2-plugin:1.4.11:deploy failed: Failed to create deployable with implementation class org.codehaus.cargo.container.tomcat.TomcatWAR for the parameters (container [id = [tomcat7x]], deployable type [war]). InvocationTargetException: Failed to parse Tomcat WAR file in [pippo-demo.war]: Failed to find file [/usr/src/app/pippo-demo.war]: /usr/src/app/pippo-demo.war (No such file or directory) -> [Help 1]

Greetings,
Roy

**Comment by balamaci** [comment]
Hi again,
Thx for reporting the image name difference. I've fixed it.

As for the second error could be that I've not only "recently"(few days) pushed pippo-demo.war to the github repo(might want to do a git pull), or you are running docker compose from another directory - there is a line that says to share the current dir contents with the image(therefore pippo-demo.war should be available at /usr/src/app inside the image.

```
  volumes:
    - .:/usr/src/app
```

Thanks again.
